# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(332E34)
$foreground = rgb(F5E4F6)
$color0 = rgb(585259)
$color1 = rgb(818245)
$color2 = rgb(AA7B30)
$color3 = rgb(B17F77)
$color4 = rgb(B18368)
$color5 = rgb(BE8457)
$color6 = rgb(AA86AC)
$color7 = rgb(E8D1E9)
$color8 = rgb(A392A3)
$color9 = rgb(ACAE5C)
$color10 = rgb(E3A440)
$color11 = rgb(ECA99E)
$color12 = rgb(EDAE8A)
$color13 = rgb(FEB074)
$color14 = rgb(E2B3E5)
$color15 = rgb(E8D1E9)

$color10_alpha = rgba(E3A44055)
$color12_alpha = rgba(EDAE8A88)
