# ==================================================
#  KoolDots (2026)
#  Project URL: https://github.com/LinuxBeginnings
#  License: GNU GPLv3
#  SPDX-License-Identifier: GPL-3.0-or-later
# ==================================================
# Commands and Apps to be executed at launch

exec-once = GSK_RENDERER=cairo swayosd-server --top-margin 0.10
exec-once = [workspace 1 silent] code
exec-once = [workspace 2 silent] kitty
exec-once = [workspace 3 silent] brave-browser
exec-once = [workspace 4 silent] slack

