# ==================================================
#  KoolDots (2026)
#  Project URL: https://github.com/LinuxBeginnings
#  License: GNU GPLv3
#  SPDX-License-Identifier: GPL-3.0-or-later
# ==================================================
# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules 
# This file will not be modified during dotfiles updates


windowrule = match:class ^(Spotify|spotify)$, opacity 0.9 0.8
windowrule = match:class ^(Slack|slack)$, opacity 0.9 0.8

layerrule = animation none, match:namespace tooltip
layerrule = animation none, match:namespace waybar

# swaync blur
layerrule = blur on, match:namespace swaync-control-center
layerrule = ignore_alpha 0.3, match:namespace swaync-control-center
layerrule = blur on, match:namespace swaync-notification-window
layerrule = ignore_alpha 0.3, match:namespace swaync-notification-window

#  Optional Layer rules
#  To Resolve blurred corners in rofi  Uncomment
# layerrule = blur on, ignore_alpha 0, match:namespace rofi


